### ISSUE TITLE
Scrolling with touchpad has poor performance

### ISSUE THREAD

**Issue by lucascampelo** [radiant-player/radiant-player-mac#275]
I have a MacBook Pro and when I try to scroll the page inside Radiant Player with touchpad, the scrollbar is freezing.
I guess the problem is related with "smooth scrolling" of mac os.

I tested scrolling with mouse and works normally, but with touchpad don't works fine.

**Comment by bilalq** [comment]
I just installed this for the first time on Mavericks, and I'm seeing this issue as well. 

(Aside from this bug, I must say, this is a pretty well made app).

**Comment by akszydelko** [comment]
I often use touchpad and it always is so annoying, it freeze a whole application even when I immediately switch to mouse scroll for the first 2-3s I cannot do anything.
I have MacBook Air with Mavericks.

I have no idea what is the problem here, but first what came to my mind is that scrolling with touchpad generates a hell lot more scroll events fired then mouse scroll.
Take a look at simple js example in [Plunker](http://plnkr.co/edit/VYhp4vBYhCIzCp7DCqow?p=preview). On touchpad even a small fingers move generates many events. While with mouse scroll the number of event to scroll from top to bottom is constant.

Maybe while scrolling, render is called so many times that it freeze the whole app, but it's just a guess. Hope a helpful one.

**Comment by bilalq** [comment]
That sounds right. Some debouncing logic thrown in should fix it.

**Comment by lucascampelo** [comment]
Thanks for the feedback. I'm using Mavericks too.
If what the @akszydelko says its right, can be solved stopping the last scroll event and start again (like some HTML5 animations).

**Comment by bilalq** [comment]
I've noticed that this only happens on my retina MBP. My older, fatter one has no problems.

**Comment by Tape** [comment]
This may actually be already fixed just not released yet, I checked out the repo and built with xcode using the instructions in the readme and I have buttery smooth scrolling now. Here's some fairly simple instructions you can follow to do so:

1. Check out repo.
* Open radiant-player-mac.xcworkspace with xcode
* Click the play icon in the top left to build
* On the left sidebar, ensure the folder icon is clicked and go to the Products folder
* Right click on Radiant Player.app and click show in finder
* Replace your existing .app file with that one.

**Comment by lucascampelo** [comment]
Don't work for me @Tape. Look out:
![captura de tela 2015-01-14 as 22 38 17](https://cloud.githubusercontent.com/assets/1775353/5750584/13622f18-9c3e-11e4-86d2-1388b469a397.png)

**Comment by Tape** [comment]
That's strange @lucascampelo, unfortunately I'm not intimate with the codebase or really OSX development in general, I managed to get it built no problem. Sorry I can't be of assistance here.

**Comment by kbhomes** [comment]
@lucascampelo @bilalq: Could you hop on over to #280 and test the pre-release version and see if performance has improved any? Thanks!

**Comment by chrismou** [comment]
Hey everyone - I know this is a ***really*** old issue, but there's been a ton of fixes/improvements since it was logged.

If possible, could you check latest code and see if you're still seeing the issues you're reporting here? You can either build from master, or for convenience I've tagged a release on my fork of everything up to today: https://github.com/chrismou/radiant-player-mac/releases/tag/v1.5.0-20151213

Thanks!
