### ISSUE TITLE
Support for previous versions of OS X

### ISSUE THREAD

**Issue by cyberjacob** [radiant-player/radiant-player-mac#277]
Only supporting 10.8 and above is likely limiting the number of people that can make use of Radiant Player. As such, adding support for previous versions of OS X would be very useful.

**Comment by jadengore** [comment]
@cyberjacob Thanks for your comment, but now since Radiant Player supports 4 versions of OS X we want to focus on more pressing issues to the application, such as performance.

I'm going to close this. cc @radiant-player/radiant-player-mac if you guys think we should support more versions, but I think it's safe to say we won't.

**Comment by jacobwgillespie** [comment]
Yeah, I'd say we're always open to PRs that improve the app for people on older systems, but with constrained developer time, we likely won't support anything older than 10.8

**Comment by jadengore** [comment]
@jacobwgillespie :+1:
