### ISSUE TITLE
OSD Dialog doesn't show currently playing song

### ISSUE THREAD

**Issue by can3p** [radiant-player/radiant-player-mac#427]
Hi! First of all, thanks for developing this great app!

I have a problem with displaying currently played song, nothing is shown, see the screen shot
OS: Mac OS X 10.10.5,
Radiant player 1.5.0

![screen shot 2015-12-01 at 11 33 02 am](https://cloud.githubusercontent.com/assets/125821/11498434/b7c8384e-981f-11e5-9627-c88790c50af1.png)

**Comment by chrismou** [comment]
Hey @can3p - I believe this was fixed in https://github.com/radiant-player/radiant-player-mac/pull/400 and should be in the next release.

In the meantime, you can either build your own binary from the master branch, or save some time by using this version I built 2 days ago as part of a (now merged) PR https://github.com/chrismou/radiant-player-mac/releases/download/v1.5.0-cyan/RadiantPlayer.app.zip - it's tagged as 1.5.0 so you should be prompted to update as normal when the next release is out.

**Comment by can3p** [comment]
This build works for me, thanks a lot!

**Comment by hico-horiuchi** [comment]
Thank you :+1:
