### ISSUE TITLE
Show album art in dock not working on El Capitan?

### ISSUE THREAD

**Issue by gholtslander-va** [radiant-player/radiant-player-mac#434]
I have the "Show album art in dock" checkbox selected but the album art is not showing up in the dock icon. Did this change in El Capitan? Here are some specs to help with debugging (maybe):

![image](https://cloud.githubusercontent.com/assets/8973794/11629215/6d161b3a-9cbc-11e5-8c0c-4b62f4d32f92.png)
Radiant Player 1.5.0

Thanks guys, it's really encouraging to see how far this repo has come in the last year and a bit.

**Comment by chrismou** [comment]
Hey @gholtslander-va 

I suspect this is another issue fixed in https://github.com/radiant-player/radiant-player-mac/pull/400 but not yet released.

Could you check to see if this is still an issue for you if you manually build a binary in Xcode from the master branch?  Alternatively, I have a pre-built binary on my fork from about a week ago when I was testing a pull request - https://github.com/chrismou/radiant-player-mac/releases/tag/v1.5.0-cyan

Let me know how you get on!

**Comment by gholtslander-va** [comment]
Yeah, it works! And I can drag the window around too :) Good times.

I'll close the issue. Thanks!

**Comment by chrismou** [comment]
Nice! Thanks for letting us know :+1:
