### ISSUE TITLE
Replace PayPal donations with Gratipay

### ISSUE THREAD

**Issue by jacobwgillespie** [radiant-player/radiant-player-mac#461]
Something to consider: https://gratipay.com/radiant-player/

**Comment by krisdestruction** [comment]
Perhaps not replace but add "in addition to"?

**Comment by jacobwgillespie** [comment]
Yeah, perhaps, though I think it's cool how payments through Gratipay flow out to the people working on the project (based on work if I understand it correctly)

**Comment by jacobwgillespie** [comment]
Our project has been approved!

**Comment by jacobwgillespie** [comment]
@radiant-player/radiant-player-mac any thoughts?

**Comment by jadengore** [comment]
@jacobwgillespie Maybe something like Square Cash too, love that service!

**Comment by chrismou** [comment]
I've not used gratispay before. How did it work?

**Comment by jacobwgillespie** [comment]
@jadengore Square Cash is awesome, though not sure how it'd work in our context...

@chrismou essentially people contribute a certain amount of money per month (could be a super small amount) and that money is owned by the "organization" account.  Eventually people who work on the project can withdraw that money into their own accounts as part of "payroll" for working on the project.  Kinda the patron model.  Anyways, I say "eventually" because Gratipay is currently reworking the payroll system so for now donations are owned by the org but don't go anywhere (this is temporary as they upgrade from v1.0 to v2.0).  Do check them out though as they're a completely "open" company and kinda fascinating to investigate.

**Comment by jacobwgillespie** [comment]
I'll ping @twolfson since he works on Gratipay.  :)

**Comment by twolfson** [comment]
Heh, more like contributed to a few times than "works on". @jacobwgillespie has got most of it right.

In the v1 model, everything aggregates into a main account and then contributors "take when they want".

In v2, they are still building out payroll but I don't know whether they are planning on keeping that model or allowing people to roll their own.

https://github.com/gratipay/gratipay.com/issues/3433

One large benefit for organizations is that all the inbound donations are transparent whereas with tools like Paypal its limited to the account holder.

One large negative is that people need to sign up for an account rather than enter credit card info. Also, it's a recurring payment -- no one-offs =/
