### ISSUE TITLE
Work with Play Midnight developer

### ISSUE THREAD

**Issue by FezVrasta** [radiant-player/radiant-player-mac#473]
You should ask Play Midnight to allow you to integrate its extension inside your player.

https://chrome.google.com/webstore/detail/play-midnight-for-google/ljmjmhjkcgfmfdhgplikncgndbdeckci

It would allow you to work just on the player features and leave the UI tweaks to him. It would be a win-win.

I know it's a Chrome extension and this app uses the Safari webview, but it's trivial to take the javascript used by @chrisxclash (the dev) and put it inside your app.

**Comment by chrisxclash** [comment]
I'd be more than happy to help contribute towards Radiant Player with my setup.

Feel free to snag the project ([here](https://github.com/chrisxclash/play-midnight)) and let me know if anything is needed from me tweaks-wise.

I'm working on redoing all of the JavaScript, but I figured you only need the CSS anyways.

**Comment by FezVrasta** [comment]
My idea would be to put the entire extension inside Radiant Player, so that we can use your settings panel to customize the theme.

Radiant Player already supports custom CSS **and** Javascripts for each theme, so it would be as easy as put the files in the right folders and it would be shown as theme instantly.

**Comment by chrisxclash** [comment]
Ah, that sounds even more awesome.

Shouldn't be too hard aside from moving the entire 'dist' folder wherever it needs to go and then just injecting the 'play-midnight.js' file. The biggest issue I can forsee is with saving your settings. Right now it's set up to use the Chrome storage sync, so that would have to be modified. Other than that, I don't think it's really tied all that much into being browser specific.

Luckily I've moved most of the save/get logic into the 'browser' module, so that could probably be modified to work with however Radiant saves.

I haven't looked into Radiant Player in a while since I don't have a Mac at work anymore, but I can poke into it unless someone else with more experience wants to give it a shot.

Thanks!

**Comment by FezVrasta** [comment]
About the chrome.storage, we could write a simple wrapper which uses by default the chrome.storage function and fallbacks to localStorage. What do you think about it?

**Comment by FezVrasta** [comment]
Or we could just rewrite that part if you prefer keep clean your code base. Even if it means that there will be a bit of fragmentation.

**Comment by chrisxclash** [comment]
The way I have it set up now, it's already pretty abstracted into it's own little wrapper that would make it really easy to update.

You can see it here: https://github.com/chrisxclash/play-midnight/blob/master/src/js/play-midnight-browser.js

Though, I'm in the process of rewriting all the JavaScript for the plugin anyways using require/browserify so I'm always up for suggestions with a better way of setting up that wrapper.

**Comment by FezVrasta** [comment]
Unfortunately I've not a lot of free time to help with these ideas.

By the way I can't find any better alternative to what I've suggested. It would be as simple as write:

```js
BR.get = function(data, cb) {
        if (chrome) {
            chrome.storage.sync.get(data, cb);
        } else { 
            var retrieved = localStorage.getItem('bgcolor');
            cb(retrieved);
        }
};
```

I've excluded the `self.port.emit` part because I'm not sure what's its purpose

**Comment by FezVrasta** [comment]
@chrisxclash about Browserify, I would suggest you to read this article first.
https://medium.com/@housecor/browserify-vs-webpack-b3d7ca08a0a9#.tbusz4fzf

**Comment by chrisxclash** [comment]
Not to worry. I can look into it when I have some time myself.

Yeah, I definitely knew it would be as easy as throwing it into Local Storage. I'll just have to do a merge of the default options and what comes back, but easy enough.

Also, the ```self.port.emit``` is the Firefox way of saving/getting settings (since the plugin was either Chrome or FF).

**Comment by chrisxclash** [comment]
I skimmed through some of the article, and it makes some good points. I've actually got a node-based configured build tool that I've been using for a while now that I can use that got rid of grunt/gulp from everything, so I'm not relying on either of those anymore.

Everything is building neatly through a Browserify build script that already does what I need. This was something I already threw together at my current job (we wrestled between WebPack and Browserify before choosing Browserify). Definitely wanted to get off the gulp/grunt train though, and I'm happy with where it's at!

**Comment by chrismou** [comment]
I've had some thoughts on this sort of functionality before - my original thoughts were just to have 2 colour pickers to cover background & foreground, but I've not had any time to even begin thinking about how to implement it.

Currently the pre-written CSS is injected into the page in a `<script>` tag on load. A huge downside to this implementation is that it means the player has to be restarted when changing themes for it to take effect.

A javascript solution would be much better, but it has it's own potential hurdles. Firstly, the controls would need to be integrated into Radiant's preferences menus, which would (I believe) mean using Objective for the controls.  Secondly, because of how it injects the themes, it would mean completely rewriting (or, potentially, removing) the current theme functionality and replacing it with this.

We could run it alongside the current theme functionality, but that could get a bit confusing - it would mean setting a base theme from within the preferences menu, and then tweaking the colours elsewhere. I'm not 100% sure that would work.

I'm not trying to put you off the idea - I'd love to see something like this in Radiant. Just throwing some potential caveats out there to consider.

**Comment by chrisxclash** [comment]
Ah yeah, I finally took a second to look at how the themes currently exist in Radiant (as I mentioned, I don't use it myself since I'm stuck on Windows at work now). Seems like yeah it would definitely be a bit of work to get it up and running properly.

I'm all for just moving the css over if people would enjoy it, or if someone wanted to point me in the right direction on how to get the js implemented properly, I'd be happy to dig into it more.

Are the current themes in Radiant able to be customized at all, or is the accent color/background static per theme?

I'll have to look more into everything, as I've yet to be able to dig in too much, but if anyone has any feedback on where to start or if they want to give it a go, feel free to let me know!

**Comment by FezVrasta** [comment]
If you get rid of all the other themes and use Play Midnight as default theme, all the other themes the users would write would be based on it.

This would mean that the user would know that all the theme and UI settings are managed trough the Play Midnight settings panel.

Also, this would allow different themes to share the same settings (accent, hidden sections, and so on).

I think it would be a great approach.

**Comment by chrismou** [comment]
@FezVrasta Unless I'm misunderstanding, if the extension was integrated as-is, wouldn't leave us with 2 separate settings sections?  So there'd be the main preferences popup window (objective-c), then we'd need to inject a link into the sidebar that would open a second settings page (javascript) just to control themes?

Behind the scenes, this would also mean preferences would need to be stored in 2 different places.

**Comment by jacobwgillespie** [comment]
I like the idea of adding a settings UI manager to @gmusic-utils that we could move more of our config into and then add a theme manager to @gmusic-utils that could style things based on the config settings.  We could store things inside localStorage, etc, and potentially sync it with Radiant for backup.

Oh, and @chrismou, we can use JS to change the theme without resorting to "styling with JS" as we can add and remove `style` or `link` elements from `head` with JS and can even manipulate the contents of inline `style` elements with JS as well.

**Comment by chrismou** [comment]
@jacobwgillespie My point was more that to avoid having 2 different styling controls we'd need to strip out the current stuff. Also, the current preferences menus are all built with Obj-C, so it's be massively disconnected from the existing preferences popup.

I'm all for JS based theme controls - I just don't like the idea of having 2 separate preferences menus in 2 places.  And to avoid that, we'd need to think up a way of integrating that into the existing menu - or completely rebuilding the existing preferences menu in JS.  If you look at https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-, he's got around it by creating a completely JS based preferences menu and injected the link into the sidebar.

**Comment by FezVrasta** [comment]
I think we could get rid of the native menu and use just the js based. It would simplify the work

**Comment by MarshallOfSound** [comment]
That @gmusic-utils ping got my attention aswell.  I think this comes back the unification of frameworks we were hoping to achieve there. 

In regards to theming I have a rather unique JS based method that you can check out here https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/Google%20Play%20Music/Resources/JS/dark-theme.js

It is some of the nastiest JS I have ever written but the concept is clear enough

@chrismou My settings are actually implemented in a native C# class and are simply triggered from the injected sidebar link.

To throw the cat amongst the pigeons here I actually think that you shouldn't have your settings menu injected inside Google Play Music.  Mac for instance has the standard "Preferences" menu option when you click on the apps name in the top left.  Moving it somewhere else for one app is counter intuative.  

Also if it becomes another modal inside GPM it is yet another thing that will be vulnerable to Googles constant CSS and HTML syntax changes.

But the one big thing to me is that a settings window should be able to be moved separately to the main window, that's just basic UX.

I would however be all for a JS based settings library if it addressed those above concerns.

**Comment by jacobwgillespie** [comment]
Yeah, I agree with @MarshallOfSound that it would be awesome to leave the UI of settings to the native implementations but use JS to manage their storage / effects.  Better than my original suggestion of implementing the UI inside @gmusic-utils for the mentioned reasons...

Anyways, on the original topic of theming, I think we should set up a "cascading" style system, so like you can set a base color and by default a lot of the elements change to that color.  But then each individual sub element could also be "overridden" to override their parent color / style.  Essentially something like CSS but implemented in JavaScript with named targets (so that they can target multiple elements on the page and so that the underlying "real" selectors could be changed when Google changes their markup).  Those named selectors + an option for direct CSS additions could comprise a theme format of sorts (could use JSON) which would provide some easy defining and sharing of themes.

Something like this (JS instead of JSON as I'm writing this directly into the GH issues text box and don't want to type quotations, but you get the idea):

```javascript
{
  name: 'My awesome theme',
  author: 'Jacob Gillespie <jacobwgillespie@gmail.com>',
  version: '1.0.0',
  styles: {
    textColor: '#000',
    artistTextColor: '#222'
  },
  overrides: {
    '.some .selector > .here': ['rule: 1', 'rule: 2']
  }
}
```

So in this case `textColor` would by default apply to `artistTextColor` unless it was overridden.  Could even set up something with object nesting so that children were represented that way:

```javascript
{
  textColor: {
    value: '#000',
    artistTextColor: {
      value: '#222'
    }
  }
}
```

Probably a bad example of of a specific proerty but still...

Then the JS would read that and build the resulting CSS to inject into the page.

That was long and rambling (I'm tired) but hopefully it makes at least some sense.  Just an idea on how we could implement a themeing system.

**Comment by MarshallOfSound** [comment]
Just an FYI for those here.  I just "cleaned up" (kinda) my theming JS and pushed it as its own separate library.  Simple enough to use, what do you guys think of it

https://github.com/MarshallOfSound/gmusic-theme.js

**Comment by chrismou** [comment]
@MarshallOfSound Ah, my mistake. I assumed from how it looked that it that it was pure JS.

@jacobwgillespie Cool, so we're agreed that sticking to the native menus is the best way forward. In terms of cascading, tbh I think @MarshallOfSound has the right idea - there only needs to be around 5 colour options, and each affects a different range of elements.  My main concern with allowing users to set their own element specific styling rules is if Google changes an element name, suddenly a ton of custom "themes" break and the average user won't know why or how to fix it.

**Comment by FezVrasta** [comment]
You could keep a database of classes to associate to the custom props.

For example:

buttons: [button, btn, fab, etc]

So you could update it when needed

**Comment by chrismou** [comment]
That sounds similar to what @MarshallOfSound has done in his theming repo (https://github.com/MarshallOfSound/gmusic-theme.js/blob/master/src/gmusic-theme.js#L84).

@jacobwgillespie's suggestion was to allow users to override specific selectors, which is a bit risky when the majority of our major issues stem from Google changing the selector names without warning.  

@MarshallOfSound I like the approach you've taken there.  As @FezVrasta suggests, there could be scope to break it down even further - it just comes down to how far before it becomes too overwhelming.  The average user will just want to separately customise the background and accent colours, and maybe the buttons. Not many people will want to use 20 different colours for different sections of text.  :-)

**Comment by jacobwgillespie** [comment]
Well not exactly the custom selector part (I think we should allow that so that themes that want to extend custom things can do so), but more that we internally group selectors into named parents and children so that they can be targeted and then when Google changes things, we simply change them on our end and the themes don't need to be updated.

**Comment by chrismou** [comment]
In terms of organising what can be customized, this sounds like we're all saying pretty much the same thing, but in slightly different ways :-)

So the key points, as I understand:

- Group selectors, as @MarshallOfSound, but possibly break it down into more groups for more customisation options
- Allow group colours to be set via the UI (in the case of our apps), but also allow selector overrides for app developers (so if something breaks outside of our predefined groups, it's up to them to fix it, not us)
- Store the choices in a transportable way - ie, your json example - so people can easily share themes if they want to

**Comment by MarshallOfSound** [comment]
For those interested in the current CSS but want to actually read it :smile_cat: here is a more CSS looking stylesheet

https://github.com/gmusic-utils/gmusic-theme.js/blob/master/lib/style.css

**Comment by chrismou** [comment]
Closing as probably no longer relevant. If we look at improvements to the theming in the current Radiant, most likely we'll look at integrating https://github.com/gmusic-utils/gmusic-theme.js
