### ISSUE TITLE
Last.fm 

### ISSUE THREAD

**Issue by dantespe** [radiant-player/radiant-player-mac#513]
Last.fm is not updated when a song is played multiple times. The first play is recorded, but no others.

**Comment by chrismou** [comment]
@dantespe How are you trying to achieve this?  Are you just playing the same song on repeat? Or something else?

**Comment by chrismou** [comment]
OK, so after testing I'm now 99% certain this is down to spam/duplication controls at last.fm's end.  I seem to be able to set the song as now playing, but it won't accept it as a scrobble more than once.

I'm going to close this ticket for now as I believe there's nothing to fix (plus I've tried it on a couple of other players and I'm seeing the same behaviour).  I've dropped a ticket onto the last.fm support pages to confirm it - if it turns out I'm wrong, I'll reopen this issue.
