### ISSUE TITLE
Google app specific passwords not allowed

### ISSUE THREAD

**Issue by mrinterweb** [radiant-player/radiant-player-mac#556]
When I try to sign in with a generated Google app password, I get the following error: "Please use your account password instead of an application-specific password."

As a general rule, I will not put my Google password into 3rd party applications (Firefox is the only exception I've made).

I have a feeling that this is something that Radiant has no control over, but I was curious if there was another option than putting in Google login credentials.

**Comment by jacobwgillespie** [comment]
Radiant is essentially an embedded Safari webview with a native app wrapper that handles the "native" integrations (keyboard shortcuts, miniplayer, etc.) so yeah, we don't have any control there as it's not an application login, it's literally the same page as going to play.google.com in Safari.

Unfortunately you'll need to use your Google credentials, but fortunately you can consider it essentially the same as Safari.

I suppose if you were being super security conscious there is an attack vector in that we do inject JavaScript into the browser view in order to funnel keyboard shortcuts from the OS to controls on the page, and funnel the playback information (like what's playing, the playback position, volume, etc.) from the page back to the app to power features like the miniplayer.  That JS could, I suppose be malicious, so for ultimate safety, feel free to browse through the code here and compile the app yourself.  Of course this is functionally no different from trusting any browser addons not to be malicious.

One other idea would be to check under Radiant's Preferences > Privacy > Use Safari's cookies.  Then you can close Radiant, log into Google Play Music in Safari, and re-open Radiant.  I'm working on the next 2.0 version of Radiant to fix various smaller issues and I'm not sure if I'll be able to keep that option around (I'll do my best) but for now that should alleviate some security concerns on your end.

**Comment by mrinterweb** [comment]
Thanks for the through answer. I was concerned with downloading a binary without an md5 checksum from a website. Your suggestion to review the source and build it myself is a good suggestion. Your option to share the Safari cookie is a great option as well. I'll start with sharing the Safari cookie. Thank you for the quick reply and help.

**Comment by jacobwgillespie** [comment]
Oh, MD5 checksum, that could be a good idea to publish.  The releases (and updates) are already signed, just the signatures are used by the updater and aren't published.  You can see them here: http://radiant-player.github.io/radiant-player-mac/appcast/appcast2.xml.

For Radiant 2.0, I'm hoping to get an actual Apple Developer identity set up and start distributing officially-signed builds.
