### ISSUE TITLE
Page doesn't load due cross-origin restriction.

### ISSUE THREAD

**Issue by alaruss** [radiant-player/radiant-player-mac#562]
When I open the RadiantPlay I get only a blank page. There is an error in the console:

`XMLHttpRequest cannot load https://play-music.gstatic.com/fe/89998d193955c1081b81e74193b6e35e/sj_srcs.html. Origin https://play.google.com is not allowed by Access-Control-Allow-Origin.`

The same happens if I open https://play.google.com/music/ in the Safari, but there I can fix it with an option "Disable Cross-Origin restriction".

**Comment by jacobwgillespie** [comment]
You likely want to un-disable that in Safari if you haven't already (hopefully you just did that for debugging) as that will open a fairly serious security hole.

This sounds like an issue on Google's side of things to me - I'd try clearing your Safari cache to see if that resolves, and otherwise wait it out or report it to Google from "Help and Feedback" in the hamburger menu.

**Comment by alaruss** [comment]
Clearing Safari cache didn't help. Looks like the only hope is Google Support.

**Comment by jacobwgillespie** [comment]
@alaruss did this fix itself?

**Comment by alaruss** [comment]
@jacobwgillespie Exactly.
