### ISSUE TITLE
Flash Player error

### ISSUE THREAD

**Issue by jesusgy** [radiant-player/radiant-player-mac#563]
Hi, I have a trouble with the app, it shows a message that says 'flash player missing'..  Can you buid the app to works with html5 please..
 thank u in advance

**Comment by jacobwgillespie** [comment]
We're working on a version that works with HTML5, but it's not yet ready.  Essentially Google only supports HTML5 on Chrome-based browsers and Radiant is Safari-based, so once we get the rewrite completed that will work.

For now, you will want to install Flash into Safari in order to get it to work - if you see a message about Flash being missing or a message about Flash being out of date, the solution for both is to go install / update Flash in Safari.

**Comment by lemonzi** [comment]
Oops! Ran into the same thing, and Flash is a no-no. I'll wait for the HTML5 version then.
