### ISSUE TITLE
Radiant Player needing access to Sequel Pro's authentication? 

### ISSUE THREAD

**Issue by MikeLund** [radiant-player/radiant-player-mac#655]
If I have Radiant Player open and try to connect to a server in Sequel Pro using SSH, I first approve the `SequelProTunnelAssistant wants to use your confidential information stored in "/Users/username/.ssh/id_rsa" in your keychain` message as normal.

However, then this popup comes:
![screen shot 2017-08-21 at 10 28 15](https://user-images.githubusercontent.com/17044744/29510431-fdecbeae-865b-11e7-9dd7-7ba247e2ad94.png)

No offense, but I don't want want a music player to have access to my SSH keychain :)
Is this just some confusing wording from Apple, or what exactly is this supposed to be?

Thanks!

Edit: note this also seems to happen with other programs that use the same keychain authentication method, such as MySQLWorkbench.

**Comment by jacobwgillespie** [comment]
This is likely something confusing with Apple - Radiant can store cookies / share login data with the keychain since it uses an embedded Safari webview, so it more or less shares data with Safari, but I have no idea why it would trigger this in connection with Sequel Pro.  My only guess would be that Sequel Pro is doing something to lock or unlock the keychain (perhaps since OSX is set to remember your SSH key password in the keychain?) that's triggering something that requires Radiant to re-authenticate with the keychain.  But nothing inside Radiant should care about SSH keys, should just be the embedded Safari webview trying to use the keychain for session data.
